### ISSUE TITLE
cli: fails to find malformed components

### ISSUE THREAD

**Issue by d4l3k** [pytorch/torchx#129]
## 🐛 Bug

If you try to load a component without a fully correct definition the CLI will throw an error about not being able to find it. In those cases we should indicate to the user that it was found but the component definition is incorrect and the errors that were found.

Module (check all that applies):
 * [ ] `torchx.spec`
 * [x] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [x] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce

1. comment out one of the arg descs in `components/utils.py`.
```

def echo(
    msg: str = "hello world", image: str = "/tmp", num_replicas: int = 1
) -> specs.AppDef:
    """
    Echos a message to stdout (calls /bin/echo)

    Args:
        msg: message to echo
        #image: image to use
        num_replicas: number of replicas to run

    """
    return specs.AppDef(
        name="echo",
        roles=[
            specs.Role(
                name="echo",
                image=image,
                entrypoint="/bin/echo",
                args=[msg],
                num_replicas=num_replicas,
            )
        ],
    )
```
1. try to run it:
```
tristanr@tristanr-arch2 ~/D/torchx (dockerver)> torchx run --scheduler local utils.echo
Traceback (most recent call last):
  File "/home/tristanr/.local/bin/torchx", line 33, in <module>
    sys.exit(load_entry_point('torchx', 'console_scripts', 'torchx')())
  File "/home/tristanr/Developer/torchx/torchx/cli/main.py", line 62, in main
    args.func(args)
  File "/home/tristanr/Developer/torchx/torchx/cli/cmd_run.py", line 97, in run
    result = runner.run_component(
  File "/home/tristanr/Developer/torchx/torchx/runner/api.py", line 135, in run_component
    raise ValueError(
ValueError: Component `utils.echo` not found. Please make sure it is one of the builtins: `torchx builtins`. Or registered via `[torchx
.components]` entry point (see: https://pytorch.org/torchx/latest/configure.html)
```

## Expected behavior

This should print the errors in the component instead of printing a `not found` error.

## Environment

 - torchx version (e.g. 0.1.0rc1): master
 - Python version: 3.9
 - OS (e.g., Linux): Linux
 - How you installed torchx (`conda`, `pip`, source, `docker`): source
 - Docker image and tag (if using docker):
 - Git commit (if installed from source):
 - Execution environment (on-prem, AWS, GCP, Azure etc):
 - Any other relevant information:

**Comment by d4l3k** [comment]
This is fixed as of https://github.com/pytorch/torchx/commit/4c9ef94fb03710a6c3e227566a29eb1da85f69ca
