### ISSUE TITLE
run --scheduler local utils.echo --mesg fails

### ISSUE THREAD

**Issue by stevebyan** [pytorch/torchx#201]
## 🐛 Bug

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [ X] `torchx.cli`
 * [ X] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce

1. install torchx
2. execute Quickstart `utils.echo --msg` example

```
(venv) smb % pip install torchx
Collecting torchx
  Using cached torchx-0.1.0b0-py3-none-any.whl (90 kB)
Requirement already satisfied: docstring-parser==0.8.1 in ./venv/lib/python3.9/site-packages (from torchx) (0.8.1)
Requirement already satisfied: pyre-extensions in ./venv/lib/python3.9/site-packages (from torchx) (0.0.22)
Requirement already satisfied: typing-inspect in ./venv/lib/python3.9/site-packages (from pyre-extensions->torchx) (0.6.0)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.9/site-packages (from pyre-extensions->torchx) (3.10.0.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./venv/lib/python3.9/site-packages (from typing-inspect->pyre-extensions->torchx) (0.4.3)
Installing collected packages: torchx
Successfully installed torchx-0.1.0b0
(venv) smb % torchx run --scheduler local utils.echo --help              
usage: torchx run ...torchx_params... echo  [-h] [--msg MSG]

App spec: Echos a message to stdout (calls /bin/echo)

optional arguments:
  -h, --help  show this help message and exit
  --msg MSG   message to echo
(venv) smb % torchx run --scheduler local utils.echo --msg "Hellow world"
{"session": "", "scheduler": "local", "api": "schedule", "app_id": null, "runcfg": "{\"image_type\": \"dir\", \"log_dir\": null}", "raw_exception": "Traceback (most recent call last):\n  File \"/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/runner/api.py\", line 202, in schedule\n    app_id = sched.schedule(dryrun_info)\n  File \"/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/schedulers/local_scheduler.py\", line 543, in schedule\n    replica = self._popen(role_name, replica_id, replica_params)\n  File \"/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/schedulers/local_scheduler.py\", line 485, in _popen\n    proc = subprocess.Popen(\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py\", line 951, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py\", line 1822, in _execute_child\n    raise child_exception_type(err_msg)\nsubprocess.SubprocessError: Exception occurred in preexec_fn.\n", "source": "<unknown>"}
Traceback (most recent call last):
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/bin/torchx", line 8, in <module>
    sys.exit(main())
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/cli/main.py", line 57, in main
    args.func(args)
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/cli/cmd_run.py", line 93, in run
    result = runner.run_component(
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/runner/api.py", line 142, in run_component
    return self.run(app, scheduler, cfg)
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/runner/api.py", line 164, in run
    return self.schedule(dryrun_info)
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/runner/api.py", line 202, in schedule
    app_id = sched.schedule(dryrun_info)
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/schedulers/local_scheduler.py", line 543, in schedule
    replica = self._popen(role_name, replica_id, replica_params)
  File "/Users/smb/Work/GIT/PrivateFederatedLearning/venv/lib/python3.9/site-packages/torchx/schedulers/local_scheduler.py", line 485, in _popen
    proc = subprocess.Popen(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1822, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```
## Expected behavior

I expected to see the command output the string `Hellow world`

## Environment

 - torchx version (e.g. 0.1.0rc1): torchx-0.1.0b0
 - Python version: 3.9.6
 - OS (e.g., Linux): MacOS 10.15.7
 - How you installed torchx (`conda`, `pip`, source, `docker`): pip, in a virtual environment
 - Docker image and tag (if using docker):
 - Git commit (if installed from source):
 - Execution environment (on-prem, AWS, GCP, Azure etc): on-prem
 - Any other relevant information:

## Additional context

I tried installing the latest torchx from source, but I get a different error. I'll submit another issue about that.

**Comment by aivanou** [comment]
Hi @stevebyan  !

Thank you for trying torchx! 
My apologies, that you wasn't able to run successfully. Currently we are revisiting some internal components of the torchx, to make them easier to use. As a result, we changed the way we work with images. 

There is a PR https://github.com/pytorch/torchx/pull/203 that will fix this bug that you are experiencing. 

In a meantime, can you please try:

    torchx run --scheduler local utils.echo --image / --msg "Hellow world"

-Aliaksandr

**Comment by d4l3k** [comment]
@stevebyan I believe this is fixed in the current release/trunk. Feel free to reopen if you're still hitting this issue
