### ISSUE TITLE
Running example app via local_cwd scheduler results in "AttributeError: module 'os' has no attribute 'set_blocking'"

### ISSUE THREAD

**Issue by algebrot** [pytorch/torchx#733]
## 🐛 Bug

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [x] `torchx.cli`
 * [x] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [x] `other`

## To Reproduce

1. On Windows, opened the Command Prompt
2. Installed TorchX CLI and dependency lib: `pip install torchx[dev]`
3. Created an example app named "my_torchx_app.py" (code below)
4. Ran the example app: `torchx run --scheduler local_cwd utils.python --script my_torchx_app.py "cora"`

Example app code for "my_torchx_app.py":
```
import sys
print(f"Hello, {sys.argv[1]}!")
```

Error message:
```
C:\Users\corae>torchx run --scheduler local_cwd utils.python --script my_torchx_app.py "cora"
←[34mtorchx←[0m ←[2m2023-05-15 13:08:49 INFO    ←[0m Tracker configurations: {}
←[34mtorchx←[0m ←[2m2023-05-15 13:08:49 INFO    ←[0m Log directory not set in scheduler cfg. Creating a temporary log dir that will be deleted on exit. To preserve log directory set the `log_dir` cfg option
←[34mtorchx←[0m ←[2m2023-05-15 13:08:49 INFO    ←[0m Log directory is: C:\Users\corae\AppData\Local\Temp\torchx_unnto2_j
Traceback (most recent call last):
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\Scripts\torchx.exe\__main__.py", line 7, in <module>
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\cli\main.py", line 116, in main
    run_main(get_sub_cmds(), argv)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\cli\main.py", line 112, in run_main
    args.func(args)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\cli\cmd_run.py", line 248, in run
    self._run(runner, args)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\cli\cmd_run.py", line 208, in _run
    app_handle = runner.run_component(
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\runner\api.py", line 186, in run_component
    return self.schedule(dryrun_info)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\runner\api.py", line 278, in schedule
    app_id = sched.schedule(dryrun_info)
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\schedulers\local_scheduler.py", line 749, in schedule
    replica = self._popen(
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\schedulers\local_scheduler.py", line 665, in _popen
    combined_ = Tee(
  File "C:\Users\corae\AppData\Local\Programs\Python\Python310\lib\site-packages\torchx\schedulers\streams.py", line 33, in __init__
    os.set_blocking(r.fileno(), False)
AttributeError: module 'os' has no attribute 'set_blocking'
``` 

## Expected behavior

Results in "AttributeError: module 'os' has no attribute 'set_blocking'"

## Environment

 - torchx version (e.g. 0.1.0rc1): torchx-0.5.0
 - Python version: 3.10.7
 - OS (e.g., Linux): Windows 10
 - How you installed torchx (`conda`, `pip`, source, `docker`): pip
 - Docker image and tag (if using docker): NA
 - Git commit (if installed from source): NA
 - Execution environment (on-prem, AWS, GCP, Azure etc): on-prem
 - Any other relevant information: Running "collect_env.py" resulted in "PermissionError: [Errno 13] Permission denied" for lines 251, 97, 14, and 63

## Additional context

I'm following the [Quickstart](https://pytorch.org/torchx/latest/quickstart.html) and am confused by this error because the Python[ os.set_blocking() method](https://www.geeksforgeeks.org/python-os-set_blocking-method/) is available on Unix only

**Comment by kiukchung** [comment]
Thanks for filing! Unfortunately at the moment we do not support for test for Windows. You could try running in a unix docker? we publish a docker image with every release. See: https://github.com/pytorch/torchx/pkgs/container/torchx

**Comment by kiukchung** [comment]
no activity closing for now. Feel free to reopen if you have additional questions!
