### ISSUE TITLE
torchx run --scheduler local utils.echo --msg "hello world" crashes

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchx#96]
## To Reproduce

1. `conda create -n torchx python=3.8`
2. `pip install torchx`
3. `torchx run --scheduler local utils.echo --help` -> works fine
4.  `torchx run --scheduler local utils.echo --msg "hello world"` -> Crashes

```
{"session": "", "scheduler": "local", "api": "schedule", "app_id": null, "runcfg": "{\"image_type\": \"dir\", \"log_dir\": null}", "raw_exception": "Traceback (most recent call last):\n  File \"/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/runner/api.py\", line 202, in schedule\n    app_id = sched.schedule(dryrun_info)\n  File \"/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/schedulers/local_scheduler.py\", line 543, in schedule\n    replica = self._popen(role_name, replica_id, replica_params)\n  File \"/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/schedulers/local_scheduler.py\", line 485, in _popen\n    proc = subprocess.Popen(\n  File \"/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/subprocess.py\", line 1705, in _execute_child\n    raise child_exception_type(err_msg)\nsubprocess.SubprocessError: Exception occurred in preexec_fn.\n", "source": "<unknown>"}
Traceback (most recent call last):
  File "/Users/marksaroufim/miniconda3/envs/torchx/bin/torchx", line 8, in <module>
    sys.exit(main())
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/cli/main.py", line 57, in main
    args.func(args)
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/cli/cmd_run.py", line 93, in run
    result = runner.run_component(
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/runner/api.py", line 142, in run_component
    return self.run(app, scheduler, cfg)
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/runner/api.py", line 164, in run
    return self.schedule(dryrun_info)
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/runner/api.py", line 202, in schedule
    app_id = sched.schedule(dryrun_info)
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/schedulers/local_scheduler.py", line 543, in schedule
    replica = self._popen(role_name, replica_id, replica_params)
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/site-packages/torchx/schedulers/local_scheduler.py", line 485, in _popen
    proc = subprocess.Popen(
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/marksaroufim/miniconda3/envs/torchx/lib/python3.8/subprocess.py", line 1705, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.

```

## Expected behavior

Not crash

## Environment

 - torchx version (e.g. 0.1.0rc1): Latest
 - Python version: 3.8
 - OS (e.g., Linux): Mac OS X
 - How you installed torchx (`conda`, `pip`, source, `docker`): conda
 - Docker image and tag (if using docker):
 - Git commit (if installed from source): master
 - Execution environment (on-prem, AWS, GCP, Azure etc): Local
 - Any other relevant information:

**Comment by kiukchung** [comment]
Thanks for reporting, torchx currently only supports running on Linux-based systems. Could you try using our docker image: https://github.com/orgs/pytorch/packages?repo_name=torchx instead?

**Comment by kiukchung** [comment]
See https://github.com/pytorch/torchx/issues/104. Closing since no response from OP.
